config/routes.rb
Ror1::Application.routes.draw do
  get "sessions/new"

resources :users
resources :sessions, :only => [:new, :create, :destroy]
  get "users/new"

  get "pages/about"
   match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signup',  :to => 'users#new'
 match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  get "pages/contact"

  resources :posts do
	resources :comments
end

  get "welcome/index"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :name, :presence => true
	validates :title, :presence => true,
	:length => {:minimum => 5}
	validates :content, :presence => true
	has_many :comments, :dependent => :destroy
	has_many :tags
	 accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
	end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence => true,
			:length   => { :maximum => 35 }
	validates :email, :presence => true,
		:format   => { :with => email_regex },
		:uniqueness => { :case_sensitive => false }
	validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
					   before_save :encrypt_password
	def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  def welcome
    @title = ""
  end
  def comments
    @title = "Comments"
  end
  def posts
    @title = "posts"
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
	
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  @title = "About"
  end

  def contact
  @title = "Contact"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
	@title = "Posts"
    @posts = Post.all
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
	@title = "Post #{params[:id]}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
	@title = "New Post"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
 
    @post = Post.find(params[:id])
	 @title = "Edit Post #{params[:id]}"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
    @title = "Sign in"
  end

   def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
	sign_in user
      redirect_to user
      end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end
	def show
    @user = User.find(params[:id])
	@title = @user.name
  end
  def create
    @user = User.new(params[:user])
    if @user.save
	sign_in @user
	flash[:success] = "You have succesfully signed up"
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
def title                                           
    base_title = "Twitter Light"  
    if @title.nil?                                   
      base_title                                      
    else
      "#{base_title} | #{@title}"                     
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
def title                                           
    base_title = "Twitter Light"  
    if @title.nil?                                   
      base_title                                      
    else
      "#{base_title} | #{@title}"                     
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
  def title                                           
    base_title = "Twitter Light"  
    if @title.nil?                                   
      base_title                                      
    else
      "#{base_title} | #{@title}"                     
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= user_from_remember_token
  end
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag "application", :debug => false %>
  <%= javascript_include_tag "application", :debug => false %>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	
  <![endif]-->    
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" 
      type="image/png" 
      href="/Favicon.png" />
</head>
<body style="background-color:#94CEDE;">
<div id="header">
<img  src='header.png' alt="header" width="100%" style="position:relative;top:-11px;" />
	

	<div class="menulinks" style="position:relative;left:20%;">
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/posts">My Posts</a></div>
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/">Home</a></div>
	<% if signed_in? %>
	<div class="butttons redondo" style="width:100px;height:30px;"><%= link_to "Profile", current_user, :id => 'm' %></div>
      
      <% end %>
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/">Friends</a></div>
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/">Followers</a></div>
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/about">About</a></div>
	<div class="butttons redondo" style="width:100px;height:30px;"><a id="m" href="/contact">Contact</a></div>
	
	<% if signed_in? %>
	<div class="butttons redondo" style="width:100px;height:30px;"><%= link_to "Sign out", signout_path, :method => :delete, :id => 'm' %></div>
      
      
      <% else %>
	  <div class="butttons redondo" style="width:100px;height:30px;"><%= link_to "Sign in", signin_path, :id => 'm'  %></div>
      
      <% end %>
	
	
</div>
<div id="colmask">
	<div id="colmid">
		<div id="colright">
			<div id="col1wrap">
				<div id="col1pad">
					<div id="col1">
						<!-- Column 1 start -->
							<% flash.each do |key, value| %>
							<div class="flash <%= key %>"><%= value %></div>
							<% end %>
							<%= yield %>
						<!-- Column 1 end -->
					</div>
				</div>

			</div>
			<div id="col2">
				<!-- Column 2 start -->
				<%= render 'posts/form2' %>
    
    <div class="list">
    <dl>
   <dt>My Interests are</dt>
   <dd>
    <ul>
     <li>Playing Guitar</li>
     <li>Watching Tv
     <ul>
     <li>Friends</li>
     <li>the big Bang theory</li>
     <li>30 rock</li>
     </ul></li>
     <li>Eating</li>
     <li>Going to the movies</li>
   </ul>
   </dd>
</dl>
	</div>
	<form >
Ingrese el numero: <input type="text" id="numero" value="0" /><br />
Factorial: <input type="text" id="Factorial" value="0" /><br />
Factorial recursivo: <input type="text" id="Factorialrecursivo" value="0" /><br />
<input type="button" value="calcular" onclick="validate()" />
</form>
				<!-- Column 2 end -->
			</div>
			<div id="col3">
				<!-- Column 3 start -->
				<h3>Things I do not understand about this layout</h3>
				<p>Why is there a mixture of percentage and pixel based layout, why does it have so many diferent divs, do they control the text or just the background. I beleive that things are moed by pixels to fit column width, but if that is the case then why is the width expressed, cant you just leave it pixel based. The percentage base is all crazy i set it at 100 percent but its like 20 % which i dont understand cause percentages are abslute!! </p>
				<h3>Things I do understand about this layout</h3>
				<p>Not much, i understand that there are different divs cause if not the backgrounds would overlap, that the mid column has been moved by 200 pixels to the right to fit the first column and that the third column is moved to the left by -400 pixels for the same reason, to move it to 200 pixels to the right of the screen but why cant you set it to 200 pixels right i dont know. I dont understan how the percentages are calculated!!!! i thought it was the percent of the father component, which is not the way things are working here, at least i think so. The third column is 100% of the mid one so it should be the same size shouldnt it!!! The backgrounds i think at least i get them, the col mask is backround of the whole page, its the real one i think, and it affects the left column cause it is the one thats directly on the page and not moved.
				</p>
				<!-- Column 3 end -->

			</div>
		</div>
	</div>
</div>
<div id="footer">
	
</div>



</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This page was made using ruby on rails for web technology 4</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>This page is maintained by Jonathan Ponce, Bugs or questions email to jpon91@yahoo.com</p>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/_form2.html.erb
<p>diego es un pija de maricon</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table style="background-color:#df2;">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1 style="background:red;">New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @post.name %>
</p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<p>
  <b>Tags:</b>
  <%= join_tags(@post) %>
</p>
 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<br />
 
<%= link_to 'Edit Post', edit_post_path(@post) %>
<%= link_to 'Back to Posts', posts_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>


app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>
	<%= image_tag "face.png", :alt => @user.name, :class => "imagenes", :size => "100x100" %>
  <%= @user.name %>
</h1>
<%= @user.name %>, <%= @user.email %>
<%= link_to user_path(@user), user_path(@user) %>
<%= link_to "Settings", edit_user_path(current_user) %>

app/views/welcome/_form2.html.erb
<p>diego es un pija de maricon</p>

app/views/welcome/index.html.erb
<h1>Welcome to twitter light a page made using ruby on rails</h1>
<p>Beta version</p>
<%= link_to "My blog", posts_path %>
<%= link_to "Sign up", signup_path %>